### ISSUE TITLE
MathProgBase timing out

### ISSUE THREAD

**Issue by mlubin** [IainNZ/PackageEvaluator.jl#107]
Cbc and Ipopt are test dependencies, so I guess building them counts towards the testing time limit instead of the installation time limit?

**Comment by IainNZ** [comment]
Yeah... and unfortunately, because MathProgBase is not tested in the same VM as Cbc etc., its building them fresh.

**Comment by mlubin** [comment]
Maybe we can switch to using GLPK, it's much faster to compile.
CC @tkelman

**Comment by IainNZ** [comment]
Still happening, maybe we do the GLPK switch? They time limit is currently 30 minutes, which I'm not keen on raising but probably could without causing much damage.

**Comment by mlubin** [comment]
Works for me

**Comment by IainNZ** [comment]
https://github.com/JuliaOpt/MathProgBase.jl/commit/cae40c54ac7f38dca41b4dc52ed3affe295627c3
