### ISSUE TITLE
Gadfly Tests Fail?

### ISSUE THREAD

**Issue by brian-j-smith** [IainNZ/PackageEvaluator.jl#113]
[Gadfly](http://pkg.julialang.org/detail/Gadfly.html) has been failing julia 0.4 testing on PkgEval for some time now, and it is not clear why.  Below is the terminal error message.  Note that the package

* passes [travis testing](https://travis-ci.org/dcjones/Gadfly.jl),
* passes testing on my local machines, and
* seems to be working fine for users.

It would be nice to get this testing issue resolved since it can affect testing of downstream packages, like [Mamba](http://pkg.julialang.org/detail/Mamba.html).  Any thoughts on why PkgEval is failing, while other testing systems are not, and what the solution might be?  Thanks.

CC: @dcjones, @timholy 

```julia
Rendering points on png backend.
FAILED!
ERROR: LoadError: Install Cairo.jl to use the PNG backend. You may need to delete /home/vagrant/.julia/lib/v0.4/Compose.ji afterwards.
 in error at error.jl:21
 in PNG at /home/vagrant/.julia/v0.4/Compose/src/Compose.jl:154
 in anonymous at /home/vagrant/.julia/v0.4/Gadfly/test/runtests.jl:112
 [inlined code] from util.jl:155
 in run_tests at /home/vagrant/.julia/v0.4/Gadfly/test/runtests.jl:154
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 in process_options at ./client.jl:308
 in _start at ./client.jl:411
while loading /home/vagrant/.julia/v0.4/Gadfly/test/runtests.jl, in expression starting on line 181
===============================[ ERROR: Gadfly ]================================

failed process: Process(`/home/vagrant/julia/bin/julia --check-bounds=yes --code-coverage=none --color=no /home/vagrant/.julia/v0.4/Gadfly/test/runtests.jl`, ProcessExited(1)) [1]

================================================================================
```

**Comment by IainNZ** [comment]
Were you testing master or the most recent released version? Also, the results haven't been updated in a while (I'm actually uploading new results now).

**Comment by IainNZ** [comment]
In the new results, which will be uploaded soon, pass on both Julia 0.3 and Julia 0.4

**Comment by brian-j-smith** [comment]
So glad to hear that!  Thanks for the update.
