### ISSUE TITLE
Mamba Tests Fail?

### ISSUE THREAD

**Issue by brian-j-smith** [IainNZ/PackageEvaluator.jl#114]
Similar to the Gadfly issue noted in #113...

[Mamba](http://pkg.julialang.org/detail/Mamba.html) has been failing julia 0.4 testing on PkgEval for some time now, and it is not clear why. Below is the terminal error message, which is coming from a call to the ``draw()`` function in Gadfly and essentially the same error that used to occur in the PkgEval testing of that package. Note that Mamba

* passes [travis testing](https://travis-ci.org/brian-j-smith/Mamba.jl),
* passes testing on my local machines, and
* seems to be working fine for users.

Any suggestions on how to resolve this?

CC: @bdeonovic, @dcjones, @timholy 

```julia
ERROR: LoadError: LoadError: Install Cairo.jl to use the PDF backend. You may need to delete /home/vagrant/.julia/lib/v0.4/Compose.ji afterwards.
 in error at error.jl:21
 in PDF at /home/vagrant/.julia/v0.4/Compose/src/Compose.jl:156
 in f at /home/vagrant/.julia/v0.4/Mamba/src/output/plot.jl:13
 in draw at /home/vagrant/.julia/v0.4/Mamba/src/output/plot.jl:40
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 [inlined code] from /home/vagrant/.julia/v0.4/Mamba/test/utils.jl:5
 in anonymous at no file:0
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 in process_options at ./client.jl:280
 in _start at ./client.jl:378
while loading /home/vagrant/.julia/v0.4/Mamba/test/../doc/tutorial/line.jl, in expression starting on line 257
while loading /home/vagrant/.julia/v0.4/Mamba/test/runtests.jl, in expression starting on line 30
================================[ ERROR: Mamba ]================================

failed process: Process(`/home/vagrant/julia/bin/julia --check-bounds=yes --code-coverage=none --color=no /home/vagrant/.julia/v0.4/Mamba/test/runtests.jl`, ProcessExited(1)) [1]

================================================================================
```

**Comment by IainNZ** [comment]
I haven't tried to reproduce, but I'd say the error message probably explains it fairly well. Heres what I bet would do it:

1. Install Gadfly
2. Pkg.test Gadfly
3. Install Mamba
4. Pkg.test Mamba

Because testing Gadfly will compile Compose with no Cairo present, and then installing Mamba will install Cairo, and then you'll get that error message.

I assume then this is a dupe of https://github.com/dcjones/Compose.jl/issues/139?

**Comment by brian-j-smith** [comment]
So, basically, Cairo is not compatible with Gadfly under certain circumstances - the one (PkgEval) scenario you mention being an example.  I'll continue this over at the Compose thread.

**Comment by IainNZ** [comment]
It all comes back to "optional dependencies", and how they don't play nice with package precompilation. PkgEval could, I guess, clear the cache of compiled packages after every package is tested, but it'd greatly increase the runtime of the whole system.

**Comment by brian-j-smith** [comment]
Oh, I think the way you're doing testing now is fine and doesn't need to be changed.  After all, it does represent a situation and uncover errors that could happen in practice.  Seeing the Cairo error and your explanation at the testing stage is useful in knowing about a potential user issue.

Having Gadfly/Compose flat out require Cairo is the first solution that came to my mind.  As you point out, optional dependencies can cause issues with precompilation.  On the other hand, the Gadfly developer would want to consider how a Cairo requirement might affect his large user base.
