### ISSUE TITLE
Vega fails, but for specific reason

### ISSUE THREAD

**Issue by randyzwitch** [IainNZ/PackageEvaluator.jl#116]
To avoid making users download `RDatasets` (since it's not a strict requirement to use Vega), I use my Travis and AppVeyor scripts to install RDatasets before running the tests.

Is there a way to achieve the same thing in your process? I don't want to add unnecessary packages to REQUIRES if I can help it.

**Comment by IainNZ** [comment]
You should put RDatasets in your test/REQUIRE file - this is used by
Pkg.test to install packages only require for testing.

**Comment by randyzwitch** [comment]
Ah, didn't realize there was such a thing. Thanks.
