### ISSUE TITLE
Testing RobotOS.jl

### ISSUE THREAD

**Issue by phobon** [IainNZ/PackageEvaluator.jl#74]
Currently tests fail because of (1) missing dependencies and (2) a need to set up a testing environment before starting Julia. 

I was trying to solve problem (2) by starting the environment in my test script but couldn't get it working. So I figured I'd just open the issue and see what you thought.

Here are the travis commands I use:
```
language: julia
julia:
  - release
  - nightly
before_install:
  - sudo apt-add-repository -y "deb http://packages.ros.org/ros/ubuntu precise main"
  - wget https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -O - | sudo apt-key add -
  - sudo apt-get update
  - sudo apt-get -y install ros-hydro-ros-base
  - sudo apt-get -y install ros-hydro-common-msgs
  - sudo rosdep init
  - rosdep update
before_script:
  - source /opt/ros/hydro/setup.sh
  - roscore &
  - sleep 5
  - python test/republish.py &
  - sleep 5
after_script:
  - killall roscore
  - killall python
  - sleep 5
```
If there isn't a simple fix for this, I suppose it would be fine to just mark the package as untestable.

**Comment by IainNZ** [comment]
Yeah thats way beyond the level of dependency/setup/teardown PkgEval is designed for, I'll just make it as untestable.

**Comment by phobon** [comment]
Thanks!
