### ISSUE TITLE
Stale data on pkg.julialang.org

### ISSUE THREAD

**Issue by aviks** [IainNZ/PackageEvaluator.jl#75]
So looking at pkg.julialang.org today (29 Jan) around 15:30 GMT, I see the last version of `Taro` as 0.1.1 

However, I updated METADATA to tag `Taro` a couple of days ago. It was merged 27 Jan 2100 GMT

Do you still need to push the website manually? Sorry to be pushy....  I just want to see how this package behaves in different environments.

**Comment by IainNZ** [comment]
Yeah I still need to push manually, although I'm not quite sure why its not up from yesterday. I've pushed it now, and Taro is showing as bumped and passing on 0.3 and 0.4.

**Comment by aviks** [comment]
As ever, thanks a ton, Iain.
