### ISSUE TITLE
Use PPAs or generic binaries, Ubuntu trusty or precise?

### ISSUE THREAD

**Issue by IainNZ** [IainNZ/PackageEvaluator.jl#78]
@staticfloat @tkelman

So I think I've finally got PackageEvaluator working in these Vagrant VMs. There was this awkwardness with segfaults which led to me experimenting with a lot of things, so now I'm doing some tidy up.

Two questions:

* I'm using the generic linux binaries. Would it better to use the PPAs? I switched to the tarballs to avoid said awkward segfaults but it didn't make a difference.
* Should I stick with Ubuntu 12 precise or switch back to 14 trusty?

**Comment by tkelman** [comment]
The PPAs tend to lag behind in dependencies, require a bit more manual intervention, and are Ubuntu-specific so I personally don't think it would be the end of the world if we thought about deprecating them eventually. The only thing we lose by encouraging people to use the Linux binaries would be in-place updates. Though @staticfloat is the one who does all the maintenance work so it's up to him really.

**Comment by staticfloat** [comment]
I don't think it's wise to get rid of the PPAs until we have a mechanism from within Julia to say "A new release is available!", along with something like `Base.upgrade()` to download a new release and get it working.  The PPA is pretty popular, with hundreds of downloads every month.  For testing purposes however, I prefer the tarballs, so I'd recommend those.  The difference between 12.04 and 14.04 is not that big, although dependencies tend to be more up-to-date on 14.04 (obviously).

**Comment by tkelman** [comment]
> with hundreds of downloads every month

Is that before or after counting downloads from Travis on packages that haven't switched over to `language: julia` yet?

**Comment by staticfloat** [comment]
After.  Here's an [ipython notebook](http://nbviewer.ipython.org/gist/staticfloat/2390dc43da3b12d2fbdb) showing download stats.  Check out those release spikes; looks like we've got an install base of around a thousand.

**Comment by tkelman** [comment]
Cool, good stuff. The D guys did their Travis setup in such a way that they set a user agent header with curl so they can filter out the Travis downloads. Wonder whether S3 gives us that fine-grained info.

Oh, and the clock is still off
```
  | | |_| | | | (_| |  |  Version 0.3.6 (2015-01-08 22:33 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org release
```

**Comment by IainNZ** [comment]
Thanks for info, I'll stick to current config for now until its super stable
