### ISSUE TITLE
libmagickwand4

### ISSUE THREAD

**Issue by timholy** [IainNZ/PackageEvaluator.jl#80]
From your mailing list post, I think I understand that your tests are being run on Ubuntu 12.04. Images is failing on installation of libmagickwand4, via a dependency on libcups2. Any idea what's up? Does it need a `sudo apt-get update && apt-get upgrade`?

**Comment by timholy** [comment]
ImageView, ProfileView, and TestImages fail for the same cause.

**Comment by IainNZ** [comment]
Thats probably it, I have the `update` and `upgrade` lines commented out because I was testing something. I'll uncomment them anyway, but I'll confirm that is the case anyway.

**Comment by IainNZ** [comment]
That seemed to do the trick, I was able to (manually) run Pkg.build("ImageView") and Pkg.test("ImageView"), although I did get the error:

```
ERROR: `width` has no method matching width(::Canvas)
 in setbb! at /home/vagrant/.julia/v0.3/ImageView/src/display.jl:82
 in resize at /home/vagrant/.julia/v0.3/ImageView/src/display.jl:518
 in view at /home/vagrant/.julia/v0.3/ImageView/src/display.jl:379
 in include at ./boot.jl:245
 in include_from_node1 at ./loading.jl:128
 in include at ./boot.jl:245
 in include_from_node1 at loading.jl:128
 in process_options at ./client.jl:285
 in _start at ./client.jl:354
while loading /home/vagrant/.julia/v0.3/ImageView/test/tile.jl, in expression starting on line 6
while loading /home/vagrant/.julia/v0.3/ImageView/test/runtests.jl, in expression starting on line 1
error during Tk callback:
```

**Comment by IainNZ** [comment]
I think I'm going to need to upgrade to Ubuntu 14, only reason I was using 12 was when working through some bugs earlier.

**Comment by IainNZ** [comment]
This lack of an update hit a few packages, e.g. Gtk, so hopefully will be much greener soon enough.

**Comment by IainNZ** [comment]
Actually given Travis seems to be running Ubuntu 12 still, I'm not sure I should update...

**Comment by timholy** [comment]
I think either should be fine.

Thanks for fixing this! I suspect the ImageView error has a different source. I'll try to look into that later today, and meanwhile close this. Thanks for your rapid response!
