### ISSUE TITLE
FunctionalData reports Bus Error

### ISSUE THREAD

**Issue by rened** [IainNZ/PackageEvaluator.jl#82]
I dont quite know how to interpret this. Running the FunctionalData unit tests locally as well as on travis works. The PkgEval test results for FunctionalData 0.0.3 reported a `MemoryError`, I dont remember where exactly, but it was also something I had never seen before.

Any hints on what I should do / try to narrow this down?

```
>>> 'using FunctionalData' log
Julia Version 0.3.6
Commit 0c24dca (2015-02-17 22:12 UTC)
Platform Info:
  System: Linux (x86_64-unknown-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E5-2650 0 @ 2.00GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Nehalem)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
/home/vagrant/testpkg/v0.3/FunctionalData

>>> test log

signal (7): Bus error
unknown function (ip: 1439565846)
unsafe_copy! at array.jl:41
copy! at array.jl:54
copy! at sharedarray.jl:290
jl_apply_generic at /home/vagrant/julia03/bin/../lib/julia/libjulia.so (unknown line)
shmap at /home/vagrant/testpkg/v0.3/FunctionalData/src/computing.jl:168
jl_apply_generic at /home/vagrant/julia03/bin/../lib/julia/libjulia.so (unknown line)
anonymous at /home/vagrant/testpkg/v0.3/FunctionalData/test/runtests.jl:348
facts at /home/vagrant/testpkg/v0.3/FactCheck/src/FactCheck.jl:286
shouldtestcontext at /home/vagrant/testpkg/v0.3/FunctionalData/test/runtests.jl:7
jl_apply_generic at /home/vagrant/julia03/bin/../lib/julia/libjulia.so (unknown line)
anonymous at /home/vagrant/testpkg/v0.3/FunctionalData/test/runtests.jl:343
facts at /home/vagrant/testpkg/v0.3/FactCheck/src/FactCheck.jl:286
shouldtest at /home/vagrant/testpkg/v0.3/FunctionalData/test/runtests.jl:6
jl_apply_generic at /home/vagrant/julia03/bin/../lib/julia/libjulia.so (unknown line)
unknown function (ip: 1458228424)
unknown function (ip: 1458224592)
unknown function (ip: 1458291626)
unknown function (ip: 1458294333)
jl_load at /home/vagrant/julia03/bin/../lib/julia/libjulia.so (unknown line)
include at ./boot.jl:245
jl_apply_generic at /home/vagrant/julia03/bin/../lib/julia/libjulia.so (unknown line)
include_from_node1 at loading.jl:128
jl_apply_generic at /home/vagrant/julia03/bin/../lib/julia/libjulia.so (unknown line)
process_options at ./client.jl:285
_start at ./client.jl:354
jlcall__start_17420 at /home/vagrant/julia03/bin/../lib/julia/sys.so (unknown line)
jl_apply_generic at /home/vagrant/julia03/bin/../lib/julia/libjulia.so (unknown line)
unknown function (ip: 4200751)
julia_trampoline at /home/vagrant/julia03/bin/../lib/julia/libjulia.so (unknown line)
unknown function (ip: 4199725)
__libc_start_main at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
unknown function (ip: 4199781)
INFO: Computing test dependencies for FunctionalData...
INFO: Installing FactCheck v0.2.5
INFO: Testing FunctionalData
```

**Comment by rened** [comment]
Ok, testing in the `releasesetup` VM is seems that using a single Julia worker for testing makes the tests pass. I'll see what I can find out.

**Comment by rened** [comment]
Ok, just an out of memory issue. fixed in 0.0.5

**Comment by IainNZ** [comment]
Hi @rened yes sorry, the MemoryError() means simply there is not enough RAM - 1 GB is available.

**Comment by rened** [comment]
No problem, it was good to learn to use the PkgEval VMs. Very nice project btw, thanks!

**Comment by IainNZ** [comment]
Thanks! I'm just really happy someone was able to fire up a VM and check :+1:

**Comment by rened** [comment]
I only realized I could actually do this when you mentioned the VMs in your email an hour ago our so, although it is clearly stated in the Readme. My mental block, I guess, came from the fact that PkgEval is simply another Julia package - I was somehow thinking this infrastructure-service and its code base is somewhere out of my reach. 

You perhaps could put a little statement on pkg.julialang.org like "This overview is powered by the PkgEval.jl package. See [link] to learn how to run these package tests locally in a VM". Also, you could make the "Report test result error" link to PkgEval's Readme instead of going directly to the issues.

**Comment by IainNZ** [comment]
I'll do that, the README wasn't particularly useful before but now it is (hopefully) it really should be the destination.
