### ISSUE TITLE
10-minute timeout is too strict

### ISSUE THREAD

**Issue by tkelman** [IainNZ/PackageEvaluator.jl#83]
CoinOptServices is failing because of this. You could set the environment variable `MAKEFLAGS="-j4"` and it'll help some, but might cause other packages to fail. I don't want to hardcode that in my `deps/build.jl`, I think it's more appropriate to leave that for the user to do manually.

**Comment by IainNZ** [comment]
Any estimate of how long it would take? I don't want to set the parallel build thing.

**Comment by tkelman** [comment]
Depends how fast your machine is. I'm trying with 20 minutes on mine right now.

**Comment by tkelman** [comment]
As an estimate, I'd say however long Cbc takes, plus however long Ipopt takes, plus another few libraries on top of that.

**Comment by IainNZ** [comment]
Yikes, thats quite a bit. I guess I could try 30 minutes and see how that goes. The only reason I added a time limit was because of this: http://pkg.julialang.org/?pkg=WCSLIB&ver=release / https://github.com/JuliaLang/BinDeps.jl/issues/129

**Comment by tkelman** [comment]
If Cbc and Ipopt run in the same instance and get built before CoinOptServices, then it would save some time. 20 minutes was not enough to build everything in serial on my old slow linux machine.

**Comment by IainNZ** [comment]
Cbc does, its alphabetical.

**Comment by tkelman** [comment]
Yeah, I see the logs do actually start with downloading Ipopt, not Cbc. So if Ipopt also runs in the same instance but after CoinOptServices, at least Ipopt should run quickly due to already being built.

**Comment by tkelman** [comment]
Bump. I don't know what'll be enough on your machine. By 10 minutes on the last run it got to partway through Couenne, which seems like it was almost done, probably? If I run Cbc first, then CoinOptServices in the same instance, on my old slow hardware I need 50 mins.

**Comment by IainNZ** [comment]
We'll try 30: https://github.com/IainNZ/PackageEvaluator.jl/commit/8125a1d8ec3a9e42c2741a3bd329b95ebaa2f170

**Comment by tkelman** [comment]
Thanks! Judging by how far your machine got in 10 vs how far mine gets in 10, I suspect it should be enough.

**Comment by tkelman** [comment]
I could also try turning off DyLP, Vol, Bcp, SYMPHONY, and anything else that gets built by default on Linux but I haven't really needed to use through osil. I wasn't planning on packaging those in Homebrew or WinRPM, for now anyway.

**Comment by tkelman** [comment]
Looks like half an hour was enough, but I think it might be running out memory during linking, right at the end of the build:
```
{standard input}: Assembler messages:
{standard input}:5609: Warning: end of file not at end of a line; newline inserted
{standard input}:5882: Error: unknown pseudo-op: `.'
g++: internal compiler error: Killed (program cc1plus)
```

**Comment by IainNZ** [comment]
Seems like this is working?

**Comment by tkelman** [comment]
I think the timeout is fine now, yeah. It might need more memory though, if those linker failures keep happening.

**Comment by tkelman** [comment]
Had another linker failure http://pkg.julialang.org/?pkg=CoinOptServices&ver=release, would it hurt anything to bump up the memory by another 512 or 1024 mb?

**Comment by IainNZ** [comment]
I'll go up another 512mb, running four in parallel so 6 GB total should be manageable. Was generally aiming to lowball it for a future scenario where it runs on AWS or the like.

**Comment by tkelman** [comment]
had another failure http://pkg.julialang.org/?pkg=CoinOptServices&ver=release, I'll PR bumping the memory to 1536 mb
