### ISSUE TITLE
'full_pass' / 'full_fail' to 'tests_pass' / 'tests_fail'?

### ISSUE THREAD

**Issue by catawbasam** [IainNZ/PackageEvaluator.jl#88]
'full_fail' in particular I find slightly mis-leading.  At first glance it looks worse than 'using_fail'.

**Comment by IainNZ** [comment]
I agree that it isn't amazingly clear at first, but this isn't really appearing in anything consumed by a person. Its short for `full_test_fail`, I guess.

**Comment by garborg** [comment]
Aren't all those orange `full_fail`s all over http://pkg.julialang.org/pulse.html consumed by people? (They always trip me up, too.)

**Comment by IainNZ** [comment]
Kinda, I guess? I think maybe 10 people ever look at it and I don't really get how you could forget what they mean (its color coded, with the description is given above). I'm guess I could take away the words and just color code it? I'm not sure there is a particularly more useful description that is the same length

**Comment by garborg** [comment]
If the page isn't for people to look at, it probably shouldn't be there. Two of three people here are confused looking at it (my guess is the misleading name overrides the helpfulness of the color coding for the two of us). I'd say the descriptions proposed by @catawbasam are significantly more useful, even if they're still not perfect.

**Comment by IainNZ** [comment]
OK, will make the change

**Comment by garborg** [comment]
Thanks, @IainNZ  -- it'll at least help some simple souls.

**Comment by catawbasam** [comment]
Thanks!  FWIW, I think the package metrics you are producing are very useful cultivating a healthy package ecosystem, and that this is critical if Julia is to succeed.
(eg https://github.com/JuliaLang/julia/issues/10596)
