### ISSUE TITLE
using PackageEvaluator.jl to check julia by example

### ISSUE THREAD

**Issue by samuelcolvin** [IainNZ/PackageEvaluator.jl#92]
Hi, perhaps this is a slightly odd question.

I'm updating [Julia By Example](http://www.scolvin.com/juliabyexample/) to test itself. That's easy with test on push with travis but I'm wonder if it would be possible to build it nightly using PackageEvaluator.jl and then display the badge?

I could add it to METADATA.jl as a package but that seems a bit perverse for something people are very unlike to want to install.

**Comment by IainNZ** [comment]
Hi @samuelcolvin, why would you want to test it nightly? Surely check it works against release Julia using Travis whenever you update it would be best?

**Comment by samuelcolvin** [comment]
I think you're probably right, that's what I'm doing.

**Comment by IainNZ** [comment]
Sounds good, it'd probably too much work to keep it going against 0.4 (and isn't really what you'd want to encourage new users to be doing anyway!)
