### ISSUE TITLE
Polyglot error

### ISSUE THREAD

**Issue by wavexx** [IainNZ/PackageEvaluator.jl#94]
"Polyglot" shows "Package doesn't load". In deps/build.jl I try to fetch a submodule, which fails with the following:

```
You need to run this command from the toplevel of the working tree.
==============================[ ERROR: Polyglot ]===============================
failed process: Process(`git submodule update --init`, ProcessExited(1)) [1]
```

Do you have better ideas for fetching submodules?
I'm giving you headaches... sorry about that :/

**Comment by IainNZ** [comment]
Did you ever figure this out?

**Comment by wavexx** [comment]
On 06/16/2015 12:41 AM, Iain Dunning wrote:
> Did you ever figure this out?

No.. it looks as if pkgeval switches to a different directory?
Is it possible?

But if I run the evaluator locally it works...

**Comment by IainNZ** [comment]
It runs it in a nonstandard directory, i.e. `~/pkgtest/.julia/`..., but thats all really.

**Comment by wavexx** [comment]
On 06/17/2015 08:29 AM, Iain Dunning wrote:
> It runs it in a nonstandard directory, i.e. `~/pkgtest/.julia/`..., but thats all really.

So that's the cwd during run("...") in deps/build.jl ?

**Comment by IainNZ** [comment]
This is still happening and as PkgEval now pretty much just does Pkg.add and Pkg.test in the default directories, I don't think this is a PackageEval problem.
