### ISSUE TITLE
Memory error

### ISSUE THREAD

**Issue by davidavdav** [IainNZ/PackageEvaluator.jl#96]
I am gettting a test result for GaussianMixtures.jl which appears to be due to lack of memory.  

What is the maximum amount of memory my package test can use?

**Comment by IainNZ** [comment]
Hi @davidavdav, each VM has 1.5 GB RAM

**Comment by IainNZ** [comment]
Which is set here: https://github.com/IainNZ/PackageEvaluator.jl/blob/ac41e0d1ebd69d001d8e2ea3fff173241286617c/scripts/Vagrantfile#L8-L10

**Comment by davidavdav** [comment]
OK, I do have a `setmem(0.1) ## GB` in `runtests.jl`---but this is only for training a GMM.  Maybe the data itself is large, but I find it odd if that were the case.  I'll do some more testing.

**Comment by IainNZ** [comment]
If you have VirtualBox and/or Vagrant, you can try the VM for yourself to see. We could increase the memory limit, but I'm trying to keep it low because 4 of these VMs run in parallel and a future host machine might not have that much RAM.
Not sure if there is actually a way to do that.
