### ISSUE TITLE
pkg.julialang.org seems to be stale

### ISSUE THREAD

**Issue by davidanthoff** [IainNZ/PackageEvaluator.jl#99]
Front page says it was last updated on 2015-09-11.

For ExcelReaders, I tagged version 0.3 13 days ago, but pkg.julialang.org only reports 0.2 (and that is also what shows up in the badges).

**Comment by IainNZ** [comment]
Could be just a weird timing thing. Cooking up a fresh batch of results now.

**Comment by IainNZ** [comment]
Looking good now
